# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dear Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dear Diary

end

target 'DearDiaryImages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DearDiaryImages

end

target 'DearDiaryStrings' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DearDiaryStrings

end

target 'DearDiaryUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DearDiaryUIKit
  pod 'SnapKit', '~> 5.0.0'
  pod 'CHTCollectionViewWaterfallLayout'
  pod 'JTAppleCalendar', '~> 7.1'

end
